[theme]
primaryColor = "#035AA6"
backgroundColor = "#F7F8FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#0F172A"
font = "sans serif"

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false
